name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cleanS
      run: make clean -C serveur/
    - name: makeS
      run: make -C serveur/
    - name: cleanC
      run: make clean -C client/
    - name: makeC
      run: make -C client/
