name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cleanS
      run: serveur/make clean
    - name: makeS
      run: serveur/make
    - name: cleanC
      run: client/make clean
    - name: makeC
      run: client/make
